// Code generated by cmd/cgo; DO NOT EDIT.

//line /home/makki/Projects/test/cgo/main.go:1:1
package main

/*
int add(int a, int b)
{
    return a + b;
}
*/
import _ "unsafe"

func main() {
	s := ( /*line :12:7*/_Cfunc_add /*line :12:11*/)(1, 2)
	println("add(1,2) =>", s)
}
